# Generated by Django 2.0.3 on 2018-03-13 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('realname', models.CharField(max_length=100)),
                ('faceimage', models.CharField(max_length=100)),
                ('phonenum', models.CharField(max_length=100)),
                ('message_type', models.IntegerField()),
                ('message_title', models.CharField(blank=True, max_length=255, null=True)),
                ('message_text', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('tasktype', models.CharField(blank=True, max_length=100, null=True)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('ranges', models.IntegerField(blank=True, null=True)),
                ('who', models.CharField(blank=True, max_length=100, null=True)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('collection_type', models.IntegerField(blank=True, null=True)),
                ('object_id', models.IntegerField()),
                ('collect_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.IntegerField()),
                ('user', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(max_length=1)),
                ('message_text', models.CharField(blank=True, max_length=140, null=True)),
                ('message_url', models.CharField(blank=True, max_length=100, null=True)),
                ('update_time', models.DateTimeField()),
                ('praise', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pageinfo', models.CharField(max_length=32)),
                ('pageinfo2', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DutyInfo',
            fields=[
                ('duty_id', models.AutoField(primary_key=True, serialize=False)),
                ('duty', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacesFeatManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('flag', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionInfo',
            fields=[
                ('function_id', models.AutoField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32)),
                ('head_image', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('time', models.DateTimeField()),
                ('context', models.TextField()),
                ('tasktype', models.CharField(max_length=32)),
                ('money', models.IntegerField()),
                ('deadline', models.CharField(max_length=12)),
                ('ranges', models.IntegerField()),
                ('who', models.CharField(max_length=32)),
                ('phonenum', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='HibernateSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_val', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jokes',
            fields=[
                ('joke_id', models.IntegerField()),
                ('joke_text', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JpushInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jpush_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('reg_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JqrUsers',
            fields=[
                ('unino', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=21, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('insert_time', models.DateTimeField()),
                ('delete_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeInfo',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('office', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('key1', models.CharField(blank=True, max_length=20, null=True)),
                ('answer', models.CharField(blank=True, max_length=512, null=True)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('good', models.IntegerField()),
                ('bad', models.IntegerField()),
                ('browse_count', models.IntegerField()),
                ('question_office', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDailyconversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_key', models.CharField(blank=True, max_length=255, null=True)),
                ('conversation_question', models.CharField(blank=True, max_length=255, null=True)),
                ('conversation_answer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFunction',
            fields=[
                ('function_id', models.AutoField(primary_key=True, serialize=False)),
                ('function_key', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('function_prior', models.IntegerField(blank=True, null=True)),
                ('function_order', models.ForeignKey(blank=True, db_column='function_order', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.FunctionInfo')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRecommender',
            fields=[
                ('qr_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('is_recommender', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommenderHistory',
            fields=[
                ('community_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recommender_user', models.CharField(max_length=255)),
                ('recommender_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_num', models.CharField(blank=True, max_length=10, null=True)),
                ('room_name', models.CharField(blank=True, max_length=20, null=True)),
                ('room_image', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SigninInfo',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_status', models.CharField(blank=True, max_length=10, null=True)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SigninType',
            fields=[
                ('signin_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sign_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StaffCheckin',
            fields=[
                ('checkin_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffCheckout',
            fields=[
                ('checkout_id', models.IntegerField(primary_key=True, serialize=False)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StaffFace',
            fields=[
                ('face_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('face_time', models.DateTimeField(blank=True, null=True)),
                ('face_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(blank=True, max_length=10, null=True)),
                ('room', models.CharField(blank=True, max_length=20, null=True)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('voice', models.CharField(blank=True, max_length=255, null=True)),
                ('sortkey', models.CharField(blank=True, max_length=20, null=True)),
                ('duty', models.ForeignKey(blank=True, db_column='duty', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.DutyInfo')),
                ('office', models.ForeignKey(blank=True, db_column='office', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.OfficeInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StaffInfo2',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(blank=True, max_length=10, null=True)),
                ('office', models.CharField(blank=True, max_length=10, null=True)),
                ('duty', models.CharField(blank=True, max_length=10, null=True)),
                ('room', models.CharField(blank=True, max_length=20, null=True)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('voice', models.CharField(blank=True, max_length=255, null=True)),
                ('sortkey', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnsolvedQuestion',
            fields=[
                ('unsolvedquestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('unsolvedquestion', models.CharField(blank=True, max_length=255, null=True)),
                ('unsolvedquestion_time', models.DateTimeField()),
                ('issolved', models.IntegerField()),
                ('solved_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('attention_id', models.IntegerField()),
                ('attention_rank', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('modify_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFeatptr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('featptr', models.CharField(max_length=5120)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(blank=True, max_length=32, null=True)),
                ('realname', models.CharField(max_length=64)),
                ('jobnum', models.CharField(max_length=64)),
                ('phonenum', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=1)),
                ('sortkey', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=64)),
                ('school', models.CharField(blank=True, max_length=64, null=True)),
                ('faceimage', models.CharField(max_length=32)),
                ('rankscore', models.IntegerField()),
                ('creditscore', models.IntegerField()),
                ('createtime', models.DateTimeField()),
                ('job', models.CharField(max_length=32)),
                ('nickname', models.CharField(blank=True, max_length=32, null=True)),
                ('sign', models.CharField(blank=True, max_length=64, null=True)),
                ('admin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('view_history', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsersFeatptr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featptr', models.TextField()),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('realname', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('voice_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('voice_text', models.CharField(blank=True, max_length=512, null=True)),
                ('voice_url', models.CharField(blank=True, max_length=255, null=True)),
                ('voice_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='unsolvedquestion',
            name='quser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.UserInfo'),
        ),
        migrations.AddField(
            model_name='staffface',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.StaffInfo'),
        ),
        migrations.AddField(
            model_name='staffcheckout',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.StaffInfo'),
        ),
        migrations.AddField(
            model_name='staffcheckin',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.StaffInfo'),
        ),
        migrations.AddField(
            model_name='community',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.UserInfo'),
        ),
    ]
